### ISSUE TITLE
hreflang is empty

### ISSUE THREAD

**Issue by RafaelKa** [neos/neos-seo#14]
All the hreflang-Tags are set incorrect.

Following snippet is rendered from Neos.Demo Site Package
Similar on my current site :/ :

```
<link rel="alternate" hreflang="" href="https://neos-2.3.dev/"/>
<link rel="alternate" hreflang="" href="https://neos-2.3.dev/uk"/>
<link rel="alternate" hreflang="" href="https://neos-2.3.dev/de"/>
<link rel="alternate" hreflang="" href="https://neos-2.3.dev/fr"/>
<link rel="alternate" hreflang="" href="https://neos-2.3.dev/nl"/>
<link rel="alternate" hreflang="" href="https://neos-2.3.dev/da"/>
<link rel="alternate" hreflang="" href="https://neos-2.3.dev/lv"/>
```

The language settings seem to be set correctly: [..../Neos.Demo/Configuration/Settings.yaml](https://github.com/neos/Neos.Demo/blob/master/Configuration/Settings.yaml#L34-L68)

```
TYPO3:
  TYPO3CR:
    contentDimensions:
      'language':
        label: 'Neos.Demo:Main:contentDimensions.language'
        icon: 'icon-language'
        default: 'en_US'
        defaultPreset: 'en_US'
        presets:
          'all': ~
          'en_US':
            label: 'English (US)'
            values: ['en_US']
            uriSegment: 'en'
          'en_UK':
            label: 'English (UK)'
            values: ['en_UK', 'en_US']
            uriSegment: 'uk'
          'de':
            label: 'German'
            values: ['de']
            uriSegment: 'de'
          'fr':
            label: 'French'
            values: ['fr']
            uriSegment: 'fr'
          'nl':
            label: 'Dutch'
            values: ['nl', 'de']
            uriSegment: 'nl'
          'da':
            label: 'Danish'
            values: ['da']
            uriSegment: 'da'
          'lv':
            label: 'Latvian'
            values: ['lv']
            uriSegment: 'lv'
```
