### ISSUE TITLE
ENHANCEMENT: Improve confusing UX for title and titleOverride

### ISSUE THREAD

**Issue by rolandschuetz** [neos/neos-seo#185]
* This is a UX enhancement.
* Version: Neos 8.3 (currently all Neos versions)

### Current Behavior
I have interviewed several editors, and the behavior of "Title" vs. "Title Override" is for non-developers completely unclear. This makes sense, since it's not explained and an integration detail. SEO experts I talked to recommend to set both with different namens, but "override" sounds like you are doing something dangerous.

<img width="315" alt="Bildschirmfoto 2024-03-29 um 20 52 08" src="https://github.com/neos/neos-seo/assets/735982/81938edf-07c2-494c-982f-54ebc43faefc">

### Recommended Behavior
Let's change the labels and also use the same placeholder logic as in the open graph data:
<img width="311" alt="Bildschirmfoto 2024-03-29 um 20 56 13" src="https://github.com/neos/neos-seo/assets/735982/42451f71-76c0-46cc-ba6e-c9c369d31e9c">

The title placeholder generation might need to be adjusted, see https://github.com/neos/neos-seo/issues/186

### Code override to test
```
'Neos.Neos:Document':
  properties:
    title:
      ui:
        label: 'Title in menus'

'Neos.Seo:TitleTagMixin':
  properties:
    titleOverride:
      ui:
        label: 'Title in the browser window'
        help:
          message: 'This title is displayed in the browser window and in search engines. It is set as the &lt;title&gt; tag in the HTML.'
        inspector:
          editorOptions:
            placeholder: 'ClientEval: node.properties.title'
```
```
'Neos.Neos:Document':
  properties:
    title:
      ui:
        label: 'Seitentitel im Menü'

'Neos.Seo:TitleTagMixin':
  properties:
    titleOverride:
      ui:
        label: 'Seitentitel im Browserfenster'
        help:
          message: 'Dieser Titel wird im Browserfenster und in Suchmaschinen angezeigt. Dazu wird er im HTML als &lt;title&gt; Tag gesetzt.'
        inspector:
          editorOptions:
            placeholder: 'ClientEval: node.properties.title'

```

### Open questions

Should we override the document title in the SEO package or where to put this change?
