### ISSUE TITLE
BUG: Hreflang shows non translated values

### ISSUE THREAD

**Issue by paavo** [neos/neos-seo#193]
This is a:
* [x] bug

* Version: "3.3.5"

### What you did
I have a site with a fallback language dimension. 
Language FR shows DE if no content is available.

### Expected Behavior
Non translated Documents should not be listed as hreflang like:

```
<link href="https://domain.tld/path/to/german-content" rel="canonical">
<link href="https://domain.tld/path/to/german-content" hreflang="x-default" rel="alternate">
<link href="https://domain.tld/path/to/german-content" hreflang="de" rel="alternate">
```

### Actual Behavior
Fallback Documents get listed as alternate, but link to the fallback-uri:

```
<link href="https://domain.tld/path/to/german-content" rel="canonical">
<link href="https://domain.tld/path/to/german-content" hreflang="x-default" rel="alternate">
<link href="https://domain.tld/path/to/german-content" hreflang="de" rel="alternate">
<link href="https://domain.tld/path/to/german-content" hreflang="fr" rel="alternate">
```
_Last line should not be shown_

---

Looks like item.state is not 'absent' when its a Fallback @jonnitto 🤔 
https://github.com/neos/neos-seo/commit/ddeee4a35fa6d8b6555ed6177a0b93796d752f2d

---

*Language Fallback* 
```
  ContentRepository:
    contentDimensions:
      language:
        label: 'Sprachen'
        icon: icon-language
        default: de
        defaultPreset: de
        presets:
          #all: ~
          de:
            label: DE
            values:
              - de
            uriSegment: ''
          fr:
            label: FR
            values:
              - fr
              - de
            uriSegment: fr
          ...  
```
